### ISSUE TITLE
Missing install steps in README

### ISSUE THREAD

**Issue by marcysutton** [eBay/mindpatterns#1]
I had this project set up on my machine for demoing automated testing, then I tried replicating it and found that I couldn't! One problem: `@ebay/makeup` seems to have been renamed on npm to `makeup-ebay`. I tried updating to that devDependency but Lasso still fails, I think because that project changed in structure. 

Can you provide install steps for this project? I was going to submit a PR but I didn't get it working again easily. Thanks!

**Comment by ianmcburnie** [comment]
@marcysutton Yeah, I'm sorry about that, there was quite a bit of churn with the makeup stuff and it's project structure did change as you say. I'm not sure when you did your clone, but if you pull in the latest [browser.json](https://github.com/ianmcburnie/mindpatterns/blob/gh-pages/browser.json) and run `npm start` I think it should just work.

I also added some install steps to the [readme](https://github.com/ianmcburnie/mindpatterns/blob/gh-pages/README.md) if it's easier for you to just re-clone and start again.

**Comment by marcysutton** [comment]
That works, thanks so much for the prompt reply! I think we can close this issue now...

**Comment by marcysutton** [comment]
Also, FYI :) https://a11ywins.tumblr.com/post/144578706413/ebays-mind-pattern-examples

**Comment by ianmcburnie** [comment]
Wow! I'm incredibly honoured to appear on a11ywins! Thanks so much Marcy!
