### ISSUE TITLE
"X" (formerly Twitter) flags the gitbook URL as potentially scammy.

### ISSUE THREAD

**Issue by fschroiff** [eBay/mindpatterns#126]
I only got `https://ebay.gitbook.io/mindpatterns` [posted](https://x.com/A11Ycollective/status/1841031800333762862) on X using a URL shortener. Clicking the shortened link results in [a warning page](https://twitter.com/safety/unsafe_link_warning?unsafe_link=https://lvl.li/3Y2Fi6O). When you choose to ignore the warning you get forwarded to the correct page. 

Trying to post the un-obfuscated link results in an error.
<img width="628" alt="image" src="https://github.com/user-attachments/assets/4307cc82-3e6d-4098-ba0b-c01884d05a9d">

I imagine it's because of the word `ebay` in the url.

**Comment by saiponnada** [comment]
Raised the issue through X.com support. Following are ref details...

```
Case# 0379152032
ref:00DA0000000K0A8.500Vp00000CyNXd:ref
```

**Comment by saiponnada** [comment]
Looks like the issue might have been fixed.
<img width="603" alt="image" src="https://github.com/user-attachments/assets/91ab4f32-6bed-4e05-a3fd-8e0401e22829">
