### ISSUE TITLE
Custom radio button cannot be checked with SPACE

### ISSUE THREAD

**Issue by marcysutton** [eBay/mindpatterns#2]
Unlike the native radio buttons (the first two demos), the custom radio built on a span element cannot be checked with the space bar. I only caught it because I had an integration test set up for it, and when I updated to the latest code my test broke. I would have fixed it but I can't quite grok the events layered on to `$item`s and `$widget`s.

**Comment by ianmcburnie** [comment]
Thanks for finding and reporting this issue!

I'm currently away on holiday but will investigate and fix at earliest opportunity.

**Comment by Zegnat** [comment]
I just did some quick testing and it looks like `enterKeyDown` and `spaceKeyDown` aren't triggered on the custom radio elements at all.

My guess is that `$widget.commonKeyDown('[role=radio]');` fails here. Listening for the two events on `$widget` works and adding `$items.commonKeyDown()` enabled the events as well.

I fixed this by binding all my listeners to `$widget`:

``` patch
@@ -70,16 +70,16 @@
             });

             // enter key submits form
-            $items.on('enterKeyDown', function onEnterKeyDown(e) {
+            $widget.on('enterKeyDown', function onEnterKeyDown(e) {
                 $form.submit();
             });

             // spacebar triggers 'check' event
-            $items.on('spaceKeyDown', function onSpaceKeyDown(e) {
-                $widget.trigger('check', this);
+            $widget.on('spaceKeyDown', function onSpaceKeyDown(e) {
+                $widget.trigger('check', $(e.originalEvent.target).closest('.customradiogroupitem'));
             });

-            $widget.commonKeyDown('[role=radio]');
+            $widget.commonKeyDown();

             // create a roving tab index on custom radios
             $widget.rovingTabindex('[role=radio]', {activeIndex: activeRadioIdx});
```

(You can get [a pre-patched jquery.customradiogroup.js](https://gist.github.com/Zegnat/4f6614b5957c119dce94083db7ef6b4a#file-jquery-customradiogroup-js) from Gist.)

Could you run that patch through your testing for me, @marcysutton?

**Comment by ianmcburnie** [comment]
This seems to be working again.
1. Open <a href="http://ianmcburnie.github.io/mindpatterns/radio/">page</a> 
2. Tab to first ARIA radio button (it should be unchecked)
3. Press SPACE
4. First ARIA radio button is now checked
