### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by manoj9788** [eBay/mindpatterns#3]
Could please add a License to this project ?

**Comment by ianmcburnie** [comment]
Done. Thank you for raising this issue!

Also, just a friendly reminder that the JS & CSS source code under each example folder is not intended to be production ready, in case that is your intent :-) The chief intention of each example is only to convey the accessibility aspects. Other aspects, such as internationalisation, fit & finish, performance, etc are not taken into account here.

Closing ticket.
