### ISSUE TITLE
Developer Guide for Fake Menu

### ISSUE THREAD

**Issue by ghost** [eBay/mindpatterns#4]
Not sure the best place to submit a PR on your gitbook. But I developed a javascript library that implements the best practices you outline for Fake Menus:

https://www.npmjs.com/package/accessible-submenu

Feel free to link it in your project since the Fake Menus says "Content coming soon" under "Development Guide":
https://ebay.gitbooks.io/mindpatterns/content/navigation/fakemenu.html#developer-guide

**Comment by ianmcburnie** [comment]
Thanks Matt! I will be sure to add it to a resources section of the Fake Menu page. This is also a timely reminder that I need to finish the developer guide. I'll try and get to that soon :-)

One thing I notice on your demo page is that the fake menu is opened and closed via an anchor tag. For the MIND patterns our guidance is that a [Click Flyout](https://ebay.gitbooks.io/mindpatterns/content/disclosure/flyout.html) (Fake Menu pattern is an *extension* of Click Flyout pattern) should always be opened via a button. 

`A link must not be the host of a click-activated flyout. Clicking the host (the link) should always navigate to the URL in this case.`

Of course there are definitely cases when we want a link to host a Fake Menu for mouse users on hover (we have several cases of this in the eBay header), and for this our solution for keyboard users is to add a "stealth" button immediately after the link. You can see this on our [demo page](http://ianmcburnie.github.io/mindpatterns/navigation/fakemenu/).

Hope this makes sense! And again thank you for contributing!

**Comment by ghost** [comment]
Thanks for the update! I shouldn't have a problem updating it to be a button instead of hyperlink. 

Out of curiosity though, if I use `<a role="button"></a>` will that suffice? I don't mind using a button, I'm just curious. If I recall correctly, I chose a hyperlink in my project for styling reasons.

**Comment by ianmcburnie** [comment]
Adding role="button" will only change the semantics, it won't add the necessary keyboard behaviour  (i.e. SPACEBAR should trigger a click event on an element described as a button). It's best to just use a button tag if you have control of the markup, as it takes care of semantics and behaviour.

**Comment by ghost** [comment]
Great, thanks for clarifying. I've updated my library to use a button.
