### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by erickzhao** [eBay/mindpatterns#9]
Hey there,

I tried accessing http://ebay.github.io/mindpatterns/ to check out examples, but the site seems to be down due to a GH pages issue. 😕

![image](https://user-images.githubusercontent.com/16010076/40943180-31cbbc6c-681e-11e8-9317-dd760611bea7.png)

**Comment by gailfrederick** [comment]
Hi Erick, We'll bring it back up in a few days - and reply here when it's back. Thanks for letting us know!

**Comment by erickzhao** [comment]
Hi, looks like everything is working!
